'use client'
import Nav from '@/components/Nav'
import { supabase } from '@/lib/supabase'
import { brl, dateBr, onlyNumber, todayStartIso } from '@/lib/format'
import { requireUser } from '@/lib/auth'
import { useEffect,useMemo,useState } from 'react'
import { Banknote, CheckCircle2, MinusCircle, PlusCircle } from 'lucide-react'

export default function Financeiro(){
  const[caixas,setCaixas]=useState<any[]>([]);const[movs,setMovs]=useState<any[]>([]);const[pagar,setPagar]=useState<any[]>([]);const[receber,setReceber]=useState<any[]>([]);const[abertura,setAbertura]=useState('0');const[valorMov,setValorMov]=useState('');const[descMov,setDescMov]=useState('');const[tipoConta,setTipoConta]=useState('pagar');const[contaDesc,setContaDesc]=useState('');const[contaValor,setContaValor]=useState('');const[venc,setVenc]=useState('')
  async function load(){await requireUser();const[c,m,p,r]=await Promise.all([supabase.from('caixas').select('*').order('aberto_em',{ascending:false}).limit(30),supabase.from('movimentos_caixa').select('*').gte('created_at',todayStartIso()).order('created_at',{ascending:false}),supabase.from('contas_pagar').select('*').order('vencimento',{ascending:true}),supabase.from('contas_receber').select('*').order('vencimento',{ascending:true})]);setCaixas(c.data||[]);setMovs(m.data||[]);setPagar(p.data||[]);setReceber(r.data||[])}
  useEffect(()=>{load()},[])
  const caixaAberto=caixas.find(c=>c.status==='aberto')
  const entrada=movs.filter(m=>['venda','suprimento'].includes(m.tipo)).reduce((a,m)=>a+Number(m.valor||0),0)
  const saida=movs.filter(m=>['sangria','pagamento_conta'].includes(m.tipo)).reduce((a,m)=>a+Number(m.valor||0),0)
  const saldoSistema=Number(caixaAberto?.saldo_inicial||0)+entrada-saida
  const totalPagar=pagar.filter(c=>c.status==='aberta').reduce((a,c)=>a+Number(c.valor||0),0)
  const totalReceber=receber.filter(c=>c.status==='aberta').reduce((a,c)=>a+Number(c.valor||0),0)
  async function abrirCaixa(){if(caixaAberto)return alert('Já existe um caixa aberto.');const{error}=await supabase.from('caixas').insert({saldo_inicial:onlyNumber(abertura),status:'aberto'});if(error)return alert(error.message);load()}
  async function fecharCaixa(){if(!caixaAberto)return;const contado=prompt('Informe o dinheiro contado no caixa:', String(saldoSistema.toFixed(2))); if(contado===null)return;const final=onlyNumber(contado);await supabase.from('caixas').update({status:'fechado',saldo_final_informado:final,saldo_final_sistema:saldoSistema,diferenca:final-saldoSistema,fechado_em:new Date().toISOString()}).eq('id',caixaAberto.id);load()}
  async function movimento(tipo:string){if(!caixaAberto)return alert('Abra o caixa primeiro.');const valor=onlyNumber(valorMov);if(valor<=0)return alert('Informe o valor.');const{error}=await supabase.from('movimentos_caixa').insert({caixa_id:caixaAberto.id,tipo,valor,descricao:descMov||tipo});if(error)return alert(error.message);setValorMov('');setDescMov('');load()}
  async function addConta(e:any){e.preventDefault();if(!contaDesc.trim()||onlyNumber(contaValor)<=0)return alert('Informe descrição e valor.');const tabela=tipoConta==='pagar'?'contas_pagar':'contas_receber';const{error}=await supabase.from(tabela).insert({descricao:contaDesc.trim(),valor:onlyNumber(contaValor),vencimento:venc||null,status:'aberta'});if(error)return alert(error.message);setContaDesc('');setContaValor('');setVenc('');load()}
  async function quitarConta(tabela:string,id:string){await supabase.from(tabela).update({status:'quitada',pago_em:new Date().toISOString()}).eq('id',id);load()}
  return <main className="page"><div className="row"><div><h1 className="title">Financeiro</h1><p className="subtitle">Caixa diário, sangria, suprimento e contas.</p></div><span className="pill"><Banknote size={15}/> Caixa</span></div>
    <div className="grid2 mt-4"><div className="card"><small>Status do caixa</small><div className="money">{caixaAberto?'Aberto':'Fechado'}</div><p className="subtitle">{caixaAberto?dateBr(caixaAberto.aberto_em):'Abra para iniciar o dia'}</p></div><div className="card"><small>Saldo sistema</small><div className="money">{brl(saldoSistema)}</div><p className="subtitle">entradas - saídas</p></div></div>
    <div className="card mt-4 space-y-2"><h2 className="section-title">Caixa diário</h2>{!caixaAberto?<><input className="input" type="number" step="0.01" placeholder="Saldo inicial" value={abertura} onChange={e=>setAbertura(e.target.value)}/><button className="btn w-full" onClick={abrirCaixa}>Abrir caixa</button></>:<><div className="grid2"><input className="input" type="number" step="0.01" placeholder="Valor" value={valorMov} onChange={e=>setValorMov(e.target.value)}/><input className="input" placeholder="Descrição" value={descMov} onChange={e=>setDescMov(e.target.value)}/></div><div className="grid2"><button className="btn" onClick={()=>movimento('suprimento')}><PlusCircle size={16}/> Suprimento</button><button className="btn-warn" onClick={()=>movimento('sangria')}><MinusCircle size={16}/> Sangria</button></div><button className="btn-danger w-full" onClick={fecharCaixa}>Fechar caixa</button></>}</div>
    <div className="grid2 mt-4"><div className="card"><small>Contas a pagar</small><div className="money">{brl(totalPagar)}</div></div><div className="card"><small>Contas a receber</small><div className="money">{brl(totalReceber)}</div></div></div>
    <form onSubmit={addConta} className="card space-y-2 mt-4"><h2 className="section-title">Nova conta</h2><select className="select" value={tipoConta} onChange={e=>setTipoConta(e.target.value)}><option value="pagar">Conta a pagar</option><option value="receber">Conta a receber</option></select><input className="input" placeholder="Descrição" value={contaDesc} onChange={e=>setContaDesc(e.target.value)}/><div className="grid2"><input className="input" type="number" step="0.01" placeholder="Valor" value={contaValor} onChange={e=>setContaValor(e.target.value)}/><input className="input" type="date" value={venc} onChange={e=>setVenc(e.target.value)}/></div><button className="btn w-full">Salvar conta</button></form>
    <h2 className="section-title mt-5">Fluxo de caixa hoje</h2><div className="card mt-2"><div className="row"><span>Entradas</span><b>{brl(entrada)}</b></div><div className="row mt-2"><span>Saídas</span><b>{brl(saida)}</b></div><div className="row mt-2"><span>Saldo</span><b>{brl(saldoSistema)}</b></div></div>
    <h2 className="section-title mt-5">Movimentos de hoje</h2>{movs.map(m=><div className="card mt-2" key={m.id}><div className="row"><div><b>{m.tipo}</b><p className="subtitle">{m.descricao||''} • {dateBr(m.created_at)}</p></div><b>{brl(m.valor)}</b></div></div>)}
    <h2 className="section-title mt-5">Contas em aberto</h2>{[...pagar.map(c=>({...c,tabela:'contas_pagar',rotulo:'Pagar'})),...receber.map(c=>({...c,tabela:'contas_receber',rotulo:'Receber'}))].filter(c=>c.status==='aberta').map(c=><div className="card mt-2" key={c.tabela+c.id}><div className="row"><div><span className={c.rotulo==='Pagar'?'pill-warn pill':'pill-blue pill'}>{c.rotulo}</span><b className="block mt-1">{c.descricao}</b><p className="subtitle">Vencimento: {c.vencimento||'sem data'}</p></div><div className="text-right"><b>{brl(c.valor)}</b><button className="btn2 mt-2" onClick={()=>quitarConta(c.tabela,c.id)}><CheckCircle2 size={16}/> Quitar</button></div></div></div>)}
    <Nav/></main>
}
