'use client'
import Nav from '@/components/Nav'
import Scanner from '@/components/Scanner'
import { supabase } from '@/lib/supabase'
import { brl, onlyNumber } from '@/lib/format'
import { requireUser } from '@/lib/auth'
import { useEffect,useMemo,useState } from 'react'
import { Edit3, PackagePlus, ScanLine, X } from 'lucide-react'
const vazio={id:'',nome:'',codigo_barras:'',categoria:'',preco_custo:'',preco_venda:'',estoque:'',estoque_minimo:'',ativo:true}
export default function Produtos(){
  const[lista,setLista]=useState<any[]>([]);const[busca,setBusca]=useState('');const[status,setStatus]=useState('ativos');const[form,setForm]=useState<any>(vazio);const[aba,setAba]=useState('lista');const[scanner,setScanner]=useState(false);const[loading,setLoading]=useState(false)
  async function load(){await requireUser();const{data}=await supabase.from('produtos').select('*').order('nome');setLista(data||[])}
  useEffect(()=>{load()},[])
  const filtrados=useMemo(()=>{const t=busca.toLowerCase().trim();return lista.filter(p=>(status==='todos'||(status==='ativos'&&p.ativo!==false)||(status==='inativos'&&p.ativo===false))&&(!t||`${p.nome} ${p.codigo_barras||''} ${p.categoria||''}`.toLowerCase().includes(t)))},[lista,busca,status])
  async function salvar(e:any){e.preventDefault();if(!form.nome.trim())return alert('Informe o nome.');setLoading(true);const payload={nome:form.nome.trim(),codigo_barras:form.codigo_barras.trim()||null,categoria:form.categoria.trim()||null,preco_custo:onlyNumber(form.preco_custo),preco_venda:onlyNumber(form.preco_venda),estoque:onlyNumber(form.estoque),estoque_minimo:onlyNumber(form.estoque_minimo),ativo:form.ativo};const resp=form.id?await supabase.from('produtos').update(payload).eq('id',form.id):await supabase.from('produtos').insert(payload);setLoading(false);if(resp.error)return alert(resp.error.message);setForm(vazio);setAba('lista');load();alert(form.id?'Produto atualizado!':'Produto cadastrado!')}
  function editar(p:any){setForm({id:p.id,nome:p.nome||'',codigo_barras:p.codigo_barras||'',categoria:p.categoria||'',preco_custo:String(p.preco_custo??''),preco_venda:String(p.preco_venda??''),estoque:String(p.estoque??''),estoque_minimo:String(p.estoque_minimo??''),ativo:p.ativo!==false});setAba('cadastro');scrollTo({top:0,behavior:'smooth'})}
  async function toggle(p:any){const{error}=await supabase.from('produtos').update({ativo:!p.ativo}).eq('id',p.id);if(error)return alert(error.message);load()}
  const totalCusto=filtrados.reduce((a,p)=>a+Number(p.estoque||0)*Number(p.preco_custo||0),0); const totalVenda=filtrados.reduce((a,p)=>a+Number(p.estoque||0)*Number(p.preco_venda||0),0)
  return <main className="page"><div className="row"><div><h1 className="title">Produtos</h1><p className="subtitle">Cadastro, edição, estoque e código de barras.</p></div><button className="btn" onClick={()=>{setForm(vazio);setAba('cadastro')}}><PackagePlus size={18}/> Novo</button></div><div className="grid2 mt-4"><button className={aba==='lista'?'btn':'btn2'} onClick={()=>setAba('lista')}>Lista</button><button className={aba==='cadastro'?'btn':'btn2'} onClick={()=>setAba('cadastro')}>{form.id?'Editar':'Cadastrar'}</button></div>
    {aba==='cadastro'&&<form onSubmit={salvar} className="card space-y-2 mt-4"><div className="row"><h2 className="section-title">{form.id?'Editar produto':'Novo produto'}</h2><button type="button" className="btn2" onClick={()=>setScanner(!scanner)}>{scanner?<X size={16}/>:<ScanLine size={16}/>} Código</button></div>{scanner&&<Scanner onDetected={(c)=>{setForm({...form,codigo_barras:c});setScanner(false)}}/>}<input className="input" placeholder="Nome do produto" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><input className="input" placeholder="Código de barras" value={form.codigo_barras} onChange={e=>setForm({...form,codigo_barras:e.target.value})}/><input className="input" placeholder="Categoria (ex: Bebidas, Limpeza)" value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}/><div className="grid2"><input className="input" type="number" step="0.01" placeholder="Preço de custo" value={form.preco_custo} onChange={e=>setForm({...form,preco_custo:e.target.value})}/><input className="input" type="number" step="0.01" placeholder="Preço de venda" value={form.preco_venda} onChange={e=>setForm({...form,preco_venda:e.target.value})}/></div><div className="grid2"><input className="input" type="number" step="0.001" placeholder="Estoque atual" value={form.estoque} onChange={e=>setForm({...form,estoque:e.target.value})}/><input className="input" type="number" step="0.001" placeholder="Estoque mínimo" value={form.estoque_minimo} onChange={e=>setForm({...form,estoque_minimo:e.target.value})}/></div><label className="card-soft flex items-center gap-2"><input type="checkbox" checked={form.ativo} onChange={e=>setForm({...form,ativo:e.target.checked})}/> Produto ativo para vender</label><button disabled={loading} className="btn w-full">{loading?'Salvando...':form.id?'Salvar alterações':'Cadastrar produto'}</button>{form.id&&<button type="button" className="btn2 w-full" onClick={()=>{setForm(vazio);setAba('lista')}}>Cancelar edição</button>}</form>}
    {aba==='lista'&&<><div className="card mt-4 space-y-2"><input className="input" placeholder="Buscar por nome, código ou categoria" value={busca} onChange={e=>setBusca(e.target.value)}/><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="ativos">Apenas ativos</option><option value="inativos">Inativos</option><option value="todos">Todos</option></select><div className="grid2"><span className="pill">{filtrados.length} produto(s)</span><span className="pill">Custo {brl(totalCusto)}</span></div><span className="pill-blue pill">Venda potencial {brl(totalVenda)}</span></div><div className="space-y-2 mt-4">{filtrados.map(p=>{const baixo=Number(p.estoque||0)<=Number(p.estoque_minimo||0);return <div className="card" key={p.id}><div className="row"><div><b>{p.nome}</b><p className="subtitle">{p.codigo_barras||'Sem código'} • {p.categoria||'Sem categoria'} • {p.ativo===false?'Inativo':'Ativo'}</p></div>{baixo&&<span className="pill-red pill">Baixo</span>}</div><div className="grid3 mt-3"><div className="card-soft"><small>Venda</small><b className="block">{brl(p.preco_venda)}</b></div><div className="card-soft"><small>Custo</small><b className="block">{brl(p.preco_custo)}</b></div><div className="card-soft"><small>Estoque</small><b className="block">{Number(p.estoque||0).toLocaleString('pt-BR')}</b></div></div><p className="subtitle mt-2">Total custo: {brl(Number(p.estoque||0)*Number(p.preco_custo||0))} • Total venda: {brl(Number(p.estoque||0)*Number(p.preco_venda||0))}</p><div className="grid2 mt-3"><button className="btn2" onClick={()=>editar(p)}><Edit3 size={16}/> Editar</button><button className={p.ativo===false?'btn':'btn-danger'} onClick={()=>toggle(p)}>{p.ativo===false?'Ativar':'Inativar'}</button></div></div>})}{filtrados.length===0&&<div className="card list-empty">Nenhum produto encontrado.</div>}</div></>}
    <Nav/></main>
}
